robot_hw:
  bus:
    - can0
  loop_frequency: 500
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  actuators:
    joint1_motor:
      bus: can0
      id: 0x001
      type: dm4340
      lp_cutoff_frequency: 10
    joint2_motor:
      bus: can0
      id: 0x002
      type: dm4340
      lp_cutoff_frequency: 10
    joint3_motor:
      bus: can0
      id: 0x003
      type: dm4340
      lp_cutoff_frequency: 10
    joint4_motor:
      bus: can0
      id: 0x004
      type: dm4310
      lp_cutoff_frequency: 10
    joint5_motor:
      bus: can0
      id: 0x005
      type: dm4310
      lp_cutoff_frequency: 10
    joint6_motor:
      bus: can0
      id: 0x006
      type: dm4310
      lp_cutoff_frequency: 10