controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
#  gravity_compensation_controller:
#    type: gravity_compensation_controller/GravityCompensationController

  arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

#  arm_trajectory_controller:
#    type: effort_controllers/JointTrajectoryController
#    joints:
#      - joint1
#      - joint2
#      - joint3
#      - joint4
#      - joint5
#      - joint6
#    gains:
#      joint1: { p: 30, i: 0.3, d: 6, i_clamp_max: 1., i_clamp_min: -1., antiwindup: true, publish_state: true }
#      joint2: { p: 30, i: 0.3, d: 8, i_clamp_max: 1., i_clamp_min: -1., antiwindup: true, publish_state: true }
#      joint3: { p: 60, i: 0.8, d: 8, i_clamp_max: 2.5, i_clamp_min: -2.5, antiwindup: true, publish_state: true }
#      joint4: { p: 8, i: 0.3, d: 0.65, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
#      joint5: { p: 5, i: 0.3, d: 0.55, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
#      joint6: { p: 2, i: 0.1, d: 0.2, i_clamp_max: 0.5, i_clamp_min: -0.5, antiwindup: true, publish_state: true }